/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.javaagent.gettingstarted;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Library {
	
	private static final Logger LOGGER = LogManager.getLogger();
	
    public boolean someLibraryMethod() {
    	LOGGER.info("someLibraryMethod");
        return true;
    }
    
    public static void main(String[] args) {
    	Library library = new Library();
    	library.someLibraryMethod();
    }
}
